pw_user_homepage:
    path:     /login
    defaults: { _controller: PWUserBundle:Security:login }

pw_user_signup:
    path: /signup
    defaults: { _controller:PWUserBundle:Security:signup}

pw_main_homepage:
    path:     /home
    defaults: { _controller: PWMainBundle:CreateAndShare:index }

pw_main_chat:
    path:      /group/{idg}/chat
    defaults: { _controller: PWMainBundle:CreateAndShare:chat }
    requirements:
        idg: \d+